//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 05:23:00 PM EST 
//


package org.cirdles.mars.cesar.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MetamorphicDetails.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MetamorphicDetails">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Calc-Silicate"/>
 *     &lt;enumeration value="Eclogite"/>
 *     &lt;enumeration value="Gneiss"/>
 *     &lt;enumeration value="Granofels"/>
 *     &lt;enumeration value="Granulite"/>
 *     &lt;enumeration value="MechanicallyBroken"/>
 *     &lt;enumeration value="Meta-Carbonate"/>
 *     &lt;enumeration value="Meta-Ultramafic"/>
 *     &lt;enumeration value="Metasedimentary"/>
 *     &lt;enumeration value="Metasomatic"/>
 *     &lt;enumeration value="Schist"/>
 *     &lt;enumeration value="Slate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MetamorphicDetails")
@XmlEnum
public enum MetamorphicDetails {

    @XmlEnumValue("Calc-Silicate")
    CALC_SILICATE("Calc-Silicate"),
    @XmlEnumValue("Eclogite")
    ECLOGITE("Eclogite"),
    @XmlEnumValue("Gneiss")
    GNEISS("Gneiss"),
    @XmlEnumValue("Granofels")
    GRANOFELS("Granofels"),
    @XmlEnumValue("Granulite")
    GRANULITE("Granulite"),
    @XmlEnumValue("MechanicallyBroken")
    MECHANICALLY_BROKEN("MechanicallyBroken"),
    @XmlEnumValue("Meta-Carbonate")
    META_CARBONATE("Meta-Carbonate"),
    @XmlEnumValue("Meta-Ultramafic")
    META_ULTRAMAFIC("Meta-Ultramafic"),
    @XmlEnumValue("Metasedimentary")
    METASEDIMENTARY("Metasedimentary"),
    @XmlEnumValue("Metasomatic")
    METASOMATIC("Metasomatic"),
    @XmlEnumValue("Schist")
    SCHIST("Schist"),
    @XmlEnumValue("Slate")
    SLATE("Slate");
    private final String value;

    MetamorphicDetails(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MetamorphicDetails fromValue(String v) {
        for (MetamorphicDetails c: MetamorphicDetails.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
