//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.10 at 05:23:00 PM EST
//


package org.cirdles.mars.cesar.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.cirdles.mars.cesar.jaxb package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserCode_QNAME = new QName("http://app.geosamples.org", "user_code");
    private final static QName _PlatformName_QNAME = new QName("http://app.geosamples.org", "platform_name");
    private final static QName _UrlDescription_QNAME = new QName("http://app.geosamples.org", "url_description");
    private final static QName _LaunchTypeName_QNAME = new QName("http://app.geosamples.org", "launch_type_name");
    private final static QName _IsPrivate_QNAME = new QName("http://app.geosamples.org", "is_private");
    private final static QName _City_QNAME = new QName("http://app.geosamples.org", "city");
    private final static QName _Purpose_QNAME = new QName("http://app.geosamples.org", "purpose");
    private final static QName _Latitude_QNAME = new QName("http://app.geosamples.org", "latitude");
    private final static QName _NavigationType_QNAME = new QName("http://app.geosamples.org", "navigation_type");
    private final static QName _Description_QNAME = new QName("http://app.geosamples.org", "description");
    private final static QName _CollectionDatePrecision_QNAME = new QName("http://app.geosamples.org", "collection_date_precision");
    private final static QName _Igsn_QNAME = new QName("http://app.geosamples.org", "igsn");
    private final static QName _CollectionEndDate_QNAME = new QName("http://app.geosamples.org", "collection_end_date");
    private final static QName _DepthMax_QNAME = new QName("http://app.geosamples.org", "depth_max");
    private final static QName _Collector_QNAME = new QName("http://app.geosamples.org", "collector");
    private final static QName _OriginalArchiveContact_QNAME = new QName("http://app.geosamples.org", "original_archive_contact");
    private final static QName _DepthMin_QNAME = new QName("http://app.geosamples.org", "depth_min");
    private final static QName _CurrentArchiveContact_QNAME = new QName("http://app.geosamples.org", "current_archive_contact");
    private final static QName _Material_QNAME = new QName("http://app.geosamples.org", "material");
    private final static QName _CollectionMethod_QNAME = new QName("http://app.geosamples.org", "collection_method");
    private final static QName _AgeUnit_QNAME = new QName("http://app.geosamples.org", "age_unit");
    private final static QName _PlatformDescr_QNAME = new QName("http://app.geosamples.org", "platform_descr");
    private final static QName _Elevation_QNAME = new QName("http://app.geosamples.org", "elevation");
    private final static QName _PrimaryLocationName_QNAME = new QName("http://app.geosamples.org", "primary_location_name");
    private final static QName _SampleComment_QNAME = new QName("http://app.geosamples.org", "sample_comment");
    private final static QName _LaunchId_QNAME = new QName("http://app.geosamples.org", "launch_id");
    private final static QName _CollectionStartDate_QNAME = new QName("http://app.geosamples.org", "collection_start_date");
    private final static QName _SampleOtherName_QNAME = new QName("http://app.geosamples.org", "sample_other_name");
    private final static QName _CollectionMethodDescr_QNAME = new QName("http://app.geosamples.org", "collection_method_descr");
    private final static QName _LocationDescription_QNAME = new QName("http://app.geosamples.org", "location_description");
    private final static QName _FieldName_QNAME = new QName("http://app.geosamples.org", "field_name");
    private final static QName _Url_QNAME = new QName("http://app.geosamples.org", "url");
    private final static QName _CruiseFieldPrgrm_QNAME = new QName("http://app.geosamples.org", "cruise_field_prgrm");
    private final static QName _ParentIgsn_QNAME = new QName("http://app.geosamples.org", "parent_igsn");
    private final static QName _CurrentArchive_QNAME = new QName("http://app.geosamples.org", "current_archive");
    private final static QName _Zone_QNAME = new QName("http://app.geosamples.org", "zone");
    private final static QName _GeologicalUnit_QNAME = new QName("http://app.geosamples.org", "geological_unit");
    private final static QName _Province_QNAME = new QName("http://app.geosamples.org", "province");
    private final static QName _PlatformType_QNAME = new QName("http://app.geosamples.org", "platform_type");
    private final static QName _LongitudeEnd_QNAME = new QName("http://app.geosamples.org", "longitude_end");
    private final static QName _VerticalDatum_QNAME = new QName("http://app.geosamples.org", "vertical_datum");
    private final static QName _LatitudeEnd_QNAME = new QName("http://app.geosamples.org", "latitude_end");
    private final static QName _AgeMax_QNAME = new QName("http://app.geosamples.org", "age_max");
    private final static QName _Longitude_QNAME = new QName("http://app.geosamples.org", "longitude");
    private final static QName _ClassificationComment_QNAME = new QName("http://app.geosamples.org", "classification_comment");
    private final static QName _SizeUnit_QNAME = new QName("http://app.geosamples.org", "size_unit");
    private final static QName _GeologicalAge_QNAME = new QName("http://app.geosamples.org", "geological_age");
    private final static QName _Country_QNAME = new QName("http://app.geosamples.org", "country");
    private final static QName _County_QNAME = new QName("http://app.geosamples.org", "county");
    private final static QName _SampleType_QNAME = new QName("http://app.geosamples.org", "sample_type");
    private final static QName _Northing_QNAME = new QName("http://app.geosamples.org", "northing");
    private final static QName _Size_QNAME = new QName("http://app.geosamples.org", "size");
    private final static QName _Name_QNAME = new QName("http://app.geosamples.org", "name");
    private final static QName _ElevationEnd_QNAME = new QName("http://app.geosamples.org", "elevation_end");
    private final static QName _PublishDate_QNAME = new QName("http://app.geosamples.org", "publish_date");
    private final static QName _CollectorDetail_QNAME = new QName("http://app.geosamples.org", "collector_detail");
    private final static QName _PrimaryLocationType_QNAME = new QName("http://app.geosamples.org", "primary_location_type");
    private final static QName _DepthScale_QNAME = new QName("http://app.geosamples.org", "depth_scale");
    private final static QName _LaunchPlatformName_QNAME = new QName("http://app.geosamples.org", "launch_platform_name");
    private final static QName _Easting_QNAME = new QName("http://app.geosamples.org", "easting");
    private final static QName _LocalityDescription_QNAME = new QName("http://app.geosamples.org", "locality_description");
    private final static QName _OriginalArchive_QNAME = new QName("http://app.geosamples.org", "original_archive");
    private final static QName _UrlType_QNAME = new QName("http://app.geosamples.org", "url_type");
    private final static QName _AgeMin_QNAME = new QName("http://app.geosamples.org", "age_min");
    private final static QName _Locality_QNAME = new QName("http://app.geosamples.org", "locality");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cirdles.mars.cesar.jaxb
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Classification }
     *
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Samples }
     *
     */
    public Samples createSamples() {
        return new Samples();
    }

    /**
     * Create an instance of {@link IgneousType }
     *
     */
    public IgneousType createIgneousType() {
        return new IgneousType();
    }

    /**
     * Create an instance of {@link Samples.Sample }
     *
     */
    public Samples.Sample createSamplesSample() {
        return new Samples.Sample();
    }

    /**
     * Create an instance of {@link Samples.Sample.ExternalUrls }
     *
     */
    public Samples.Sample.ExternalUrls createSamplesSampleExternalUrls() {
        return new Samples.Sample.ExternalUrls();
    }

    /**
     * Create an instance of {@link Classification.Rock }
     *
     */
    public Classification.Rock createClassificationRock() {
        return new Classification.Rock();
    }

    /**
     * Create an instance of {@link Classification.Rock.Xenolithic }
     *
     */
    public Classification.Rock.Xenolithic createClassificationRockXenolithic() {
        return new Classification.Rock.Xenolithic();
    }

    /**
     * Create an instance of {@link Classification.Biology }
     *
     */
    public Classification.Biology createClassificationBiology() {
        return new Classification.Biology();
    }

    /**
     * Create an instance of {@link Classification.Mineral }
     *
     */
    public Classification.Mineral createClassificationMineral() {
        return new Classification.Mineral();
    }

    /**
     * Create an instance of {@link IgneousType.Plutonic }
     *
     */
    public IgneousType.Plutonic createIgneousTypePlutonic() {
        return new IgneousType.Plutonic();
    }

    /**
     * Create an instance of {@link IgneousType.Volcanic }
     *
     */
    public IgneousType.Volcanic createIgneousTypeVolcanic() {
        return new IgneousType.Volcanic();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleOtherNames }
     *
     */
    public Samples.Sample.SampleOtherNames createSamplesSampleSampleOtherNames() {
        return new Samples.Sample.SampleOtherNames();
    }

    /**
     * Create an instance of {@link Samples.Sample.ExternalUrls.ExternalUrl }
     *
     */
    public Samples.Sample.ExternalUrls.ExternalUrl createSamplesSampleExternalUrlsExternalUrl() {
        return new Samples.Sample.ExternalUrls.ExternalUrl();
    }

    /**
     * Create an instance of {@link Classification.Rock.Metamorphic }
     *
     */
    public Classification.Rock.Metamorphic createClassificationRockMetamorphic() {
        return new Classification.Rock.Metamorphic();
    }

    /**
     * Create an instance of {@link Classification.Rock.Ore }
     *
     */
    public Classification.Rock.Ore createClassificationRockOre() {
        return new Classification.Rock.Ore();
    }

    /**
     * Create an instance of {@link Classification.Rock.Sedimentary }
     *
     */
    public Classification.Rock.Sedimentary createClassificationRockSedimentary() {
        return new Classification.Rock.Sedimentary();
    }

    /**
     * Create an instance of {@link Classification.Rock.Xenolithic.Metamorphic }
     *
     */
    public Classification.Rock.Xenolithic.Metamorphic createClassificationRockXenolithicMetamorphic() {
        return new Classification.Rock.Xenolithic.Metamorphic();
    }

    /**
     * Create an instance of {@link Classification.Biology.Macrobiology }
     *
     */
    public Classification.Biology.Macrobiology createClassificationBiologyMacrobiology() {
        return new Classification.Biology.Macrobiology();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "user_code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserCode(String value) {
        return new JAXBElement<String>(_UserCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "platform_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlatformName(String value) {
        return new JAXBElement<String>(_PlatformName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "url_description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUrlDescription(String value) {
        return new JAXBElement<String>(_UrlDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "launch_type_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLaunchTypeName(String value) {
        return new JAXBElement<String>(_LaunchTypeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "is_private", defaultValue = "0")
    public JAXBElement<BigInteger> createIsPrivate(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsPrivate_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "city")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "purpose")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPurpose(String value) {
        return new JAXBElement<String>(_Purpose_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "latitude")
    public JAXBElement<BigDecimal> createLatitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Latitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "navigation_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNavigationType(String value) {
        return new JAXBElement<String>(_NavigationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "collection_date_precision")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollectionDatePrecision(String value) {
        return new JAXBElement<String>(_CollectionDatePrecision_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "igsn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIgsn(String value) {
        return new JAXBElement<String>(_Igsn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "collection_end_date")
    public JAXBElement<XMLGregorianCalendar> createCollectionEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CollectionEndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "depth_max")
    public JAXBElement<BigDecimal> createDepthMax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DepthMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "collector")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollector(String value) {
        return new JAXBElement<String>(_Collector_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "original_archive_contact")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOriginalArchiveContact(String value) {
        return new JAXBElement<String>(_OriginalArchiveContact_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "depth_min")
    public JAXBElement<BigDecimal> createDepthMin(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DepthMin_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "current_archive_contact")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCurrentArchiveContact(String value) {
        return new JAXBElement<String>(_CurrentArchiveContact_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "material")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMaterial(String value) {
        return new JAXBElement<String>(_Material_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "collection_method")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollectionMethod(String value) {
        return new JAXBElement<String>(_CollectionMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "age_unit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAgeUnit(String value) {
        return new JAXBElement<String>(_AgeUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "platform_descr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlatformDescr(String value) {
        return new JAXBElement<String>(_PlatformDescr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "elevation")
    public JAXBElement<BigDecimal> createElevation(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Elevation_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "primary_location_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrimaryLocationName(String value) {
        return new JAXBElement<String>(_PrimaryLocationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "sample_comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSampleComment(String value) {
        return new JAXBElement<String>(_SampleComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "launch_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLaunchId(String value) {
        return new JAXBElement<String>(_LaunchId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "collection_start_date")
    public JAXBElement<XMLGregorianCalendar> createCollectionStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CollectionStartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "sample_other_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSampleOtherName(String value) {
        return new JAXBElement<String>(_SampleOtherName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "collection_method_descr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollectionMethodDescr(String value) {
        return new JAXBElement<String>(_CollectionMethodDescr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "location_description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLocationDescription(String value) {
        return new JAXBElement<String>(_LocationDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "field_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFieldName(String value) {
        return new JAXBElement<String>(_FieldName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "cruise_field_prgrm")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCruiseFieldPrgrm(String value) {
        return new JAXBElement<String>(_CruiseFieldPrgrm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "parent_igsn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParentIgsn(String value) {
        return new JAXBElement<String>(_ParentIgsn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "current_archive")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCurrentArchive(String value) {
        return new JAXBElement<String>(_CurrentArchive_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "zone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createZone(String value) {
        return new JAXBElement<String>(_Zone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "geological_unit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGeologicalUnit(String value) {
        return new JAXBElement<String>(_GeologicalUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "province")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProvince(String value) {
        return new JAXBElement<String>(_Province_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "platform_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlatformType(String value) {
        return new JAXBElement<String>(_PlatformType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "longitude_end")
    public JAXBElement<BigDecimal> createLongitudeEnd(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_LongitudeEnd_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "vertical_datum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVerticalDatum(String value) {
        return new JAXBElement<String>(_VerticalDatum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "latitude_end")
    public JAXBElement<BigDecimal> createLatitudeEnd(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_LatitudeEnd_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "age_max")
    public JAXBElement<BigDecimal> createAgeMax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AgeMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "longitude")
    public JAXBElement<BigDecimal> createLongitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Longitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "classification_comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createClassificationComment(String value) {
        return new JAXBElement<String>(_ClassificationComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "size_unit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSizeUnit(String value) {
        return new JAXBElement<String>(_SizeUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "geological_age")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGeologicalAge(String value) {
        return new JAXBElement<String>(_GeologicalAge_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "country")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "county")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCounty(String value) {
        return new JAXBElement<String>(_County_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "sample_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSampleType(String value) {
        return new JAXBElement<String>(_SampleType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "northing")
    public JAXBElement<BigDecimal> createNorthing(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Northing_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "size")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSize(String value) {
        return new JAXBElement<String>(_Size_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "elevation_end")
    public JAXBElement<BigDecimal> createElevationEnd(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ElevationEnd_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "publish_date")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPublishDate(String value) {
        return new JAXBElement<String>(_PublishDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "collector_detail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCollectorDetail(String value) {
        return new JAXBElement<String>(_CollectorDetail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "primary_location_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrimaryLocationType(String value) {
        return new JAXBElement<String>(_PrimaryLocationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "depth_scale")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDepthScale(String value) {
        return new JAXBElement<String>(_DepthScale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "launch_platform_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLaunchPlatformName(String value) {
        return new JAXBElement<String>(_LaunchPlatformName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "easting")
    public JAXBElement<BigDecimal> createEasting(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Easting_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "locality_description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLocalityDescription(String value) {
        return new JAXBElement<String>(_LocalityDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "original_archive")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOriginalArchive(String value) {
        return new JAXBElement<String>(_OriginalArchive_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "url_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUrlType(String value) {
        return new JAXBElement<String>(_UrlType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "age_min")
    public JAXBElement<BigDecimal> createAgeMin(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AgeMin_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://app.geosamples.org", name = "locality")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLocality(String value) {
        return new JAXBElement<String>(_Locality_QNAME, String.class, null, value);
    }

}
