//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.10 at 05:23:00 PM EST
//


package org.cirdles.mars.cesar.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sample" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{http://app.geosamples.org}user_code"/>
 *                   &lt;element ref="{http://app.geosamples.org}sample_type"/>
 *                   &lt;element ref="{http://app.geosamples.org}name"/>
 *                   &lt;element ref="{http://app.geosamples.org}material"/>
 *                   &lt;element ref="{http://app.geosamples.org}igsn" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}parent_igsn" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}is_private" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}publish_date" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}classification" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}classification_comment" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}field_name" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}description" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}age_min" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}age_max" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}age_unit" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}geological_age" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}geological_unit" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}collection_method" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}collection_method_descr" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}size" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}size_unit" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}sample_comment" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}purpose" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}latitude" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}longitude" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}latitude_end" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}longitude_end" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}elevation" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}elevation_end" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}vertical_datum" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}northing" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}easting" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}zone" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}navigation_type" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}primary_location_type" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}primary_location_name" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}location_description" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}locality" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}locality_description" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}country" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}province" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}county" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}city" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}cruise_field_prgrm" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}platform_type" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}platform_name" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}platform_descr" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}launch_platform_name" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}launch_id" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}launch_type_name" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}collector" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}collector_detail" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}collection_start_date" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}collection_end_date" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}collection_date_precision" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}current_archive" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}current_archive_contact" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}original_archive" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}original_archive_contact" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}depth_min" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}depth_max" minOccurs="0"/>
 *                   &lt;element ref="{http://app.geosamples.org}depth_scale" minOccurs="0"/>
 *                   &lt;element name="sample_other_names" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://app.geosamples.org}sample_other_name" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="external_urls" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="external_url" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://app.geosamples.org}url"/>
 *                                       &lt;element ref="{http://app.geosamples.org}description" minOccurs="0"/>
 *                                       &lt;element ref="{http://app.geosamples.org}url_type" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sample"
})
@XmlRootElement(name = "samples")
public class Samples {

    @XmlElement(required = true)
    protected List<Samples.Sample> sample;

    /**
     * Gets the value of the sample property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sample property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSample().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Samples.Sample }
     *
     *
     */
    public List<Samples.Sample> getSample() {
        if (sample == null) {
            sample = new ArrayList<Samples.Sample>();
        }
        return this.sample;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{http://app.geosamples.org}user_code"/>
     *         &lt;element ref="{http://app.geosamples.org}sample_type"/>
     *         &lt;element ref="{http://app.geosamples.org}name"/>
     *         &lt;element ref="{http://app.geosamples.org}material"/>
     *         &lt;element ref="{http://app.geosamples.org}igsn" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}parent_igsn" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}is_private" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}publish_date" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}classification" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}classification_comment" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}field_name" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}description" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}age_min" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}age_max" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}age_unit" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}geological_age" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}geological_unit" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}collection_method" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}collection_method_descr" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}size" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}size_unit" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}sample_comment" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}purpose" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}latitude" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}longitude" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}latitude_end" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}longitude_end" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}elevation" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}elevation_end" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}vertical_datum" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}northing" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}easting" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}zone" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}navigation_type" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}primary_location_type" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}primary_location_name" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}location_description" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}locality" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}locality_description" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}country" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}province" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}county" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}city" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}cruise_field_prgrm" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}platform_type" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}platform_name" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}platform_descr" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}launch_platform_name" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}launch_id" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}launch_type_name" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}collector" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}collector_detail" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}collection_start_date" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}collection_end_date" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}collection_date_precision" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}current_archive" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}current_archive_contact" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}original_archive" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}original_archive_contact" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}depth_min" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}depth_max" minOccurs="0"/>
     *         &lt;element ref="{http://app.geosamples.org}depth_scale" minOccurs="0"/>
     *         &lt;element name="sample_other_names" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://app.geosamples.org}sample_other_name" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="external_urls" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="external_url" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://app.geosamples.org}url"/>
     *                             &lt;element ref="{http://app.geosamples.org}description" minOccurs="0"/>
     *                             &lt;element ref="{http://app.geosamples.org}url_type" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Sample {

        @XmlElement(name = "user_code", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String userCode;
        @XmlElement(name = "sample_type", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String sampleType;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String name;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String material;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String igsn;
        @XmlElement(name = "parent_igsn")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String parentIgsn;
        @XmlElement(name = "is_private", defaultValue = "0")
        protected BigInteger isPrivate;
        @XmlElement(name = "publish_date")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String publishDate;
        protected Classification classification;
        @XmlElement(name = "classification_comment")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String classificationComment;
        @XmlElement(name = "field_name")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String fieldName;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String description;
        @XmlElement(name = "age_min")
        protected BigDecimal ageMin;
        @XmlElement(name = "age_max")
        protected BigDecimal ageMax;
        @XmlElement(name = "age_unit")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String ageUnit;
        @XmlElement(name = "geological_age")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String geologicalAge;
        @XmlElement(name = "geological_unit")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String geologicalUnit;
        @XmlElement(name = "collection_method")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String collectionMethod;
        @XmlElement(name = "collection_method_descr")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String collectionMethodDescr;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String size;
        @XmlElement(name = "size_unit")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String sizeUnit;
        @XmlElement(name = "sample_comment")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String sampleComment;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String purpose;
        protected BigDecimal latitude;
        protected BigDecimal longitude;
        @XmlElement(name = "latitude_end")
        protected BigDecimal latitudeEnd;
        @XmlElement(name = "longitude_end")
        protected BigDecimal longitudeEnd;
        protected BigDecimal elevation;
        @XmlElement(name = "elevation_end")
        protected BigDecimal elevationEnd;
        @XmlElement(name = "vertical_datum")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String verticalDatum;
        protected BigDecimal northing;
        protected BigDecimal easting;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String zone;
        @XmlElement(name = "navigation_type")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String navigationType;
        @XmlElement(name = "primary_location_type")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String primaryLocationType;
        @XmlElement(name = "primary_location_name")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String primaryLocationName;
        @XmlElement(name = "location_description")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String locationDescription;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String locality;
        @XmlElement(name = "locality_description")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String localityDescription;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String country;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String province;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String county;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String city;
        @XmlElement(name = "cruise_field_prgrm")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String cruiseFieldPrgrm;
        @XmlElement(name = "platform_type")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String platformType;
        @XmlElement(name = "platform_name")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String platformName;
        @XmlElement(name = "platform_descr")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String platformDescr;
        @XmlElement(name = "launch_platform_name")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String launchPlatformName;
        @XmlElement(name = "launch_id")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String launchId;
        @XmlElement(name = "launch_type_name")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String launchTypeName;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String collector;
        @XmlElement(name = "collector_detail")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String collectorDetail;
        @XmlElement(name = "collection_start_date")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar collectionStartDate;
        @XmlElement(name = "collection_end_date")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar collectionEndDate;
        @XmlElement(name = "collection_date_precision")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String collectionDatePrecision;
        @XmlElement(name = "current_archive")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String currentArchive;
        @XmlElement(name = "current_archive_contact")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String currentArchiveContact;
        @XmlElement(name = "original_archive")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String originalArchive;
        @XmlElement(name = "original_archive_contact")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String originalArchiveContact;
        @XmlElement(name = "depth_min")
        protected BigDecimal depthMin;
        @XmlElement(name = "depth_max")
        protected BigDecimal depthMax;
        @XmlElement(name = "depth_scale")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String depthScale;
        @XmlElement(name = "sample_other_names")
        protected Samples.Sample.SampleOtherNames sampleOtherNames;
        @XmlElement(name = "external_urls")
        protected Samples.Sample.ExternalUrls externalUrls;

        /**
         * Gets the value of the userCode property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getUserCode() {
            return userCode;
        }

        /**
         * Sets the value of the userCode property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setUserCode(String value) {
            this.userCode = value;
        }

        /**
         * Gets the value of the sampleType property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSampleType() {
            return sampleType;
        }

        /**
         * Sets the value of the sampleType property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSampleType(String value) {
            this.sampleType = value;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the material property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getMaterial() {
            return material;
        }

        /**
         * Sets the value of the material property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setMaterial(String value) {
            this.material = value;
        }

        /**
         * Gets the value of the igsn property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getIgsn() {
            return igsn;
        }

        /**
         * Sets the value of the igsn property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setIgsn(String value) {
            this.igsn = value;
        }

        /**
         * Gets the value of the parentIgsn property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getParentIgsn() {
            return parentIgsn;
        }

        /**
         * Sets the value of the parentIgsn property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setParentIgsn(String value) {
            this.parentIgsn = value;
        }

        /**
         * Gets the value of the isPrivate property.
         *
         * @return
         *     possible object is
         *     {@link BigInteger }
         *
         */
        public BigInteger getIsPrivate() {
            return isPrivate;
        }

        /**
         * Sets the value of the isPrivate property.
         *
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *
         */
        public void setIsPrivate(BigInteger value) {
            this.isPrivate = value;
        }

        /**
         * Gets the value of the publishDate property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPublishDate() {
            return publishDate;
        }

        /**
         * Sets the value of the publishDate property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPublishDate(String value) {
            this.publishDate = value;
        }

        /**
         * Gets the value of the classification property.
         *
         * @return
         *     possible object is
         *     {@link Classification }
         *
         */
        public Classification getClassification() {
            return classification;
        }

        /**
         * Sets the value of the classification property.
         *
         * @param value
         *     allowed object is
         *     {@link Classification }
         *
         */
        public void setClassification(Classification value) {
            this.classification = value;
        }

        /**
         * Gets the value of the classificationComment property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getClassificationComment() {
            return classificationComment;
        }

        /**
         * Sets the value of the classificationComment property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setClassificationComment(String value) {
            this.classificationComment = value;
        }

        /**
         * Gets the value of the fieldName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFieldName() {
            return fieldName;
        }

        /**
         * Sets the value of the fieldName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFieldName(String value) {
            this.fieldName = value;
        }

        /**
         * Gets the value of the description property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the ageMin property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getAgeMin() {
            return ageMin;
        }

        /**
         * Sets the value of the ageMin property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setAgeMin(BigDecimal value) {
            this.ageMin = value;
        }

        /**
         * Gets the value of the ageMax property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getAgeMax() {
            return ageMax;
        }

        /**
         * Sets the value of the ageMax property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setAgeMax(BigDecimal value) {
            this.ageMax = value;
        }

        /**
         * Gets the value of the ageUnit property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAgeUnit() {
            return ageUnit;
        }

        /**
         * Sets the value of the ageUnit property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAgeUnit(String value) {
            this.ageUnit = value;
        }

        /**
         * Gets the value of the geologicalAge property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getGeologicalAge() {
            return geologicalAge;
        }

        /**
         * Sets the value of the geologicalAge property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setGeologicalAge(String value) {
            this.geologicalAge = value;
        }

        /**
         * Gets the value of the geologicalUnit property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getGeologicalUnit() {
            return geologicalUnit;
        }

        /**
         * Sets the value of the geologicalUnit property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setGeologicalUnit(String value) {
            this.geologicalUnit = value;
        }

        /**
         * Gets the value of the collectionMethod property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCollectionMethod() {
            return collectionMethod;
        }

        /**
         * Sets the value of the collectionMethod property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCollectionMethod(String value) {
            this.collectionMethod = value;
        }

        /**
         * Gets the value of the collectionMethodDescr property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCollectionMethodDescr() {
            return collectionMethodDescr;
        }

        /**
         * Sets the value of the collectionMethodDescr property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCollectionMethodDescr(String value) {
            this.collectionMethodDescr = value;
        }

        /**
         * Gets the value of the size property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSize(String value) {
            this.size = value;
        }

        /**
         * Gets the value of the sizeUnit property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSizeUnit() {
            return sizeUnit;
        }

        /**
         * Sets the value of the sizeUnit property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSizeUnit(String value) {
            this.sizeUnit = value;
        }

        /**
         * Gets the value of the sampleComment property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSampleComment() {
            return sampleComment;
        }

        /**
         * Sets the value of the sampleComment property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSampleComment(String value) {
            this.sampleComment = value;
        }

        /**
         * Gets the value of the purpose property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPurpose() {
            return purpose;
        }

        /**
         * Sets the value of the purpose property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPurpose(String value) {
            this.purpose = value;
        }

        /**
         * Gets the value of the latitude property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getLatitude() {
            return latitude;
        }

        /**
         * Sets the value of the latitude property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setLatitude(BigDecimal value) {
            this.latitude = value;
        }

        /**
         * Gets the value of the longitude property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setLongitude(BigDecimal value) {
            this.longitude = value;
        }

        /**
         * Gets the value of the latitudeEnd property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getLatitudeEnd() {
            return latitudeEnd;
        }

        /**
         * Sets the value of the latitudeEnd property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setLatitudeEnd(BigDecimal value) {
            this.latitudeEnd = value;
        }

        /**
         * Gets the value of the longitudeEnd property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getLongitudeEnd() {
            return longitudeEnd;
        }

        /**
         * Sets the value of the longitudeEnd property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setLongitudeEnd(BigDecimal value) {
            this.longitudeEnd = value;
        }

        /**
         * Gets the value of the elevation property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getElevation() {
            return elevation;
        }

        /**
         * Sets the value of the elevation property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setElevation(BigDecimal value) {
            this.elevation = value;
        }

        /**
         * Gets the value of the elevationEnd property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getElevationEnd() {
            return elevationEnd;
        }

        /**
         * Sets the value of the elevationEnd property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setElevationEnd(BigDecimal value) {
            this.elevationEnd = value;
        }

        /**
         * Gets the value of the verticalDatum property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getVerticalDatum() {
            return verticalDatum;
        }

        /**
         * Sets the value of the verticalDatum property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setVerticalDatum(String value) {
            this.verticalDatum = value;
        }

        /**
         * Gets the value of the northing property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getNorthing() {
            return northing;
        }

        /**
         * Sets the value of the northing property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setNorthing(BigDecimal value) {
            this.northing = value;
        }

        /**
         * Gets the value of the easting property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getEasting() {
            return easting;
        }

        /**
         * Sets the value of the easting property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setEasting(BigDecimal value) {
            this.easting = value;
        }

        /**
         * Gets the value of the zone property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getZone() {
            return zone;
        }

        /**
         * Sets the value of the zone property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setZone(String value) {
            this.zone = value;
        }

        /**
         * Gets the value of the navigationType property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getNavigationType() {
            return navigationType;
        }

        /**
         * Sets the value of the navigationType property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setNavigationType(String value) {
            this.navigationType = value;
        }

        /**
         * Gets the value of the primaryLocationType property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPrimaryLocationType() {
            return primaryLocationType;
        }

        /**
         * Sets the value of the primaryLocationType property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPrimaryLocationType(String value) {
            this.primaryLocationType = value;
        }

        /**
         * Gets the value of the primaryLocationName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPrimaryLocationName() {
            return primaryLocationName;
        }

        /**
         * Sets the value of the primaryLocationName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPrimaryLocationName(String value) {
            this.primaryLocationName = value;
        }

        /**
         * Gets the value of the locationDescription property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLocationDescription() {
            return locationDescription;
        }

        /**
         * Sets the value of the locationDescription property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLocationDescription(String value) {
            this.locationDescription = value;
        }

        /**
         * Gets the value of the locality property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLocality() {
            return locality;
        }

        /**
         * Sets the value of the locality property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLocality(String value) {
            this.locality = value;
        }

        /**
         * Gets the value of the localityDescription property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLocalityDescription() {
            return localityDescription;
        }

        /**
         * Sets the value of the localityDescription property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLocalityDescription(String value) {
            this.localityDescription = value;
        }

        /**
         * Gets the value of the country property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the province property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getProvince() {
            return province;
        }

        /**
         * Sets the value of the province property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setProvince(String value) {
            this.province = value;
        }

        /**
         * Gets the value of the county property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCounty() {
            return county;
        }

        /**
         * Sets the value of the county property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCounty(String value) {
            this.county = value;
        }

        /**
         * Gets the value of the city property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the cruiseFieldPrgrm property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCruiseFieldPrgrm() {
            return cruiseFieldPrgrm;
        }

        /**
         * Sets the value of the cruiseFieldPrgrm property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCruiseFieldPrgrm(String value) {
            this.cruiseFieldPrgrm = value;
        }

        /**
         * Gets the value of the platformType property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPlatformType() {
            return platformType;
        }

        /**
         * Sets the value of the platformType property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPlatformType(String value) {
            this.platformType = value;
        }

        /**
         * Gets the value of the platformName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPlatformName() {
            return platformName;
        }

        /**
         * Sets the value of the platformName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPlatformName(String value) {
            this.platformName = value;
        }

        /**
         * Gets the value of the platformDescr property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPlatformDescr() {
            return platformDescr;
        }

        /**
         * Sets the value of the platformDescr property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPlatformDescr(String value) {
            this.platformDescr = value;
        }

        /**
         * Gets the value of the launchPlatformName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLaunchPlatformName() {
            return launchPlatformName;
        }

        /**
         * Sets the value of the launchPlatformName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLaunchPlatformName(String value) {
            this.launchPlatformName = value;
        }

        /**
         * Gets the value of the launchId property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLaunchId() {
            return launchId;
        }

        /**
         * Sets the value of the launchId property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLaunchId(String value) {
            this.launchId = value;
        }

        /**
         * Gets the value of the launchTypeName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLaunchTypeName() {
            return launchTypeName;
        }

        /**
         * Sets the value of the launchTypeName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLaunchTypeName(String value) {
            this.launchTypeName = value;
        }

        /**
         * Gets the value of the collector property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCollector() {
            return collector;
        }

        /**
         * Sets the value of the collector property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCollector(String value) {
            this.collector = value;
        }

        /**
         * Gets the value of the collectorDetail property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCollectorDetail() {
            return collectorDetail;
        }

        /**
         * Sets the value of the collectorDetail property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCollectorDetail(String value) {
            this.collectorDetail = value;
        }

        /**
         * Gets the value of the collectionStartDate property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getCollectionStartDate() {
            return collectionStartDate;
        }

        /**
         * Sets the value of the collectionStartDate property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setCollectionStartDate(XMLGregorianCalendar value) {
            this.collectionStartDate = value;
        }

        /**
         * Gets the value of the collectionEndDate property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getCollectionEndDate() {
            return collectionEndDate;
        }

        /**
         * Sets the value of the collectionEndDate property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setCollectionEndDate(XMLGregorianCalendar value) {
            this.collectionEndDate = value;
        }

        /**
         * Gets the value of the collectionDatePrecision property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCollectionDatePrecision() {
            return collectionDatePrecision;
        }

        /**
         * Sets the value of the collectionDatePrecision property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCollectionDatePrecision(String value) {
            this.collectionDatePrecision = value;
        }

        /**
         * Gets the value of the currentArchive property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCurrentArchive() {
            return currentArchive;
        }

        /**
         * Sets the value of the currentArchive property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCurrentArchive(String value) {
            this.currentArchive = value;
        }

        /**
         * Gets the value of the currentArchiveContact property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCurrentArchiveContact() {
            return currentArchiveContact;
        }

        /**
         * Sets the value of the currentArchiveContact property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCurrentArchiveContact(String value) {
            this.currentArchiveContact = value;
        }

        /**
         * Gets the value of the originalArchive property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOriginalArchive() {
            return originalArchive;
        }

        /**
         * Sets the value of the originalArchive property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOriginalArchive(String value) {
            this.originalArchive = value;
        }

        /**
         * Gets the value of the originalArchiveContact property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getOriginalArchiveContact() {
            return originalArchiveContact;
        }

        /**
         * Sets the value of the originalArchiveContact property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setOriginalArchiveContact(String value) {
            this.originalArchiveContact = value;
        }

        /**
         * Gets the value of the depthMin property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getDepthMin() {
            return depthMin;
        }

        /**
         * Sets the value of the depthMin property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setDepthMin(BigDecimal value) {
            this.depthMin = value;
        }

        /**
         * Gets the value of the depthMax property.
         *
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *
         */
        public BigDecimal getDepthMax() {
            return depthMax;
        }

        /**
         * Sets the value of the depthMax property.
         *
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *
         */
        public void setDepthMax(BigDecimal value) {
            this.depthMax = value;
        }

        /**
         * Gets the value of the depthScale property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDepthScale() {
            return depthScale;
        }

        /**
         * Sets the value of the depthScale property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDepthScale(String value) {
            this.depthScale = value;
        }

        /**
         * Gets the value of the sampleOtherNames property.
         *
         * @return
         *     possible object is
         *     {@link Samples.Sample.SampleOtherNames }
         *
         */
        public Samples.Sample.SampleOtherNames getSampleOtherNames() {
            return sampleOtherNames;
        }

        /**
         * Sets the value of the sampleOtherNames property.
         *
         * @param value
         *     allowed object is
         *     {@link Samples.Sample.SampleOtherNames }
         *
         */
        public void setSampleOtherNames(Samples.Sample.SampleOtherNames value) {
            this.sampleOtherNames = value;
        }

        /**
         * Gets the value of the externalUrls property.
         *
         * @return
         *     possible object is
         *     {@link Samples.Sample.ExternalUrls }
         *
         */
        public Samples.Sample.ExternalUrls getExternalUrls() {
            return externalUrls;
        }

        /**
         * Sets the value of the externalUrls property.
         *
         * @param value
         *     allowed object is
         *     {@link Samples.Sample.ExternalUrls }
         *
         */
        public void setExternalUrls(Samples.Sample.ExternalUrls value) {
            this.externalUrls = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="external_url" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://app.geosamples.org}url"/>
         *                   &lt;element ref="{http://app.geosamples.org}description" minOccurs="0"/>
         *                   &lt;element ref="{http://app.geosamples.org}url_type" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "externalUrl"
        })
        public static class ExternalUrls {

            @XmlElement(name = "external_url", required = true)
            protected List<Samples.Sample.ExternalUrls.ExternalUrl> externalUrl;

            /**
             * Gets the value of the externalUrl property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the externalUrl property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExternalUrl().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Samples.Sample.ExternalUrls.ExternalUrl }
             *
             *
             */
            public List<Samples.Sample.ExternalUrls.ExternalUrl> getExternalUrl() {
                if (externalUrl == null) {
                    externalUrl = new ArrayList<Samples.Sample.ExternalUrls.ExternalUrl>();
                }
                return this.externalUrl;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://app.geosamples.org}url"/>
             *         &lt;element ref="{http://app.geosamples.org}description" minOccurs="0"/>
             *         &lt;element ref="{http://app.geosamples.org}url_type" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "url",
                "description",
                "urlType"
            })
            public static class ExternalUrl {

                @XmlElement(required = true)
                protected String url;
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                protected String description;
                @XmlElement(name = "url_type")
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                protected String urlType;

                /**
                 * Gets the value of the url property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the description property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the urlType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getUrlType() {
                    return urlType;
                }

                /**
                 * Sets the value of the urlType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setUrlType(String value) {
                    this.urlType = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://app.geosamples.org}sample_other_name" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sampleOtherName"
        })
        public static class SampleOtherNames {

            @XmlElement(name = "sample_other_name", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected List<String> sampleOtherName;

            /**
             * Gets the value of the sampleOtherName property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sampleOtherName property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSampleOtherName().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             *
             *
             */
            public List<String> getSampleOtherName() {
                if (sampleOtherName == null) {
                    sampleOtherName = new ArrayList<String>();
                }
                return this.sampleOtherName;
            }

        }

    }

}
