//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 05:23:00 PM EST 
//


package org.cirdles.mars.cesar.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SedimentaryDetails.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SedimentaryDetails">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Carbonate"/>
 *     &lt;enumeration value="ConglomerateAndOrBreccia"/>
 *     &lt;enumeration value="Evaporite"/>
 *     &lt;enumeration value="GlacialAndOrPaleosol"/>
 *     &lt;enumeration value="Hybrid"/>
 *     &lt;enumeration value="Ironstone"/>
 *     &lt;enumeration value="MixedCarbAndOrSiliciclastic"/>
 *     &lt;enumeration value="MnNoduleAndOrCrust"/>
 *     &lt;enumeration value="SiliceousBiogenic"/>
 *     &lt;enumeration value="Siliciclastic"/>
 *     &lt;enumeration value="Volcaniclastic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SedimentaryDetails")
@XmlEnum
public enum SedimentaryDetails {

    @XmlEnumValue("Carbonate")
    CARBONATE("Carbonate"),
    @XmlEnumValue("ConglomerateAndOrBreccia")
    CONGLOMERATE_AND_OR_BRECCIA("ConglomerateAndOrBreccia"),
    @XmlEnumValue("Evaporite")
    EVAPORITE("Evaporite"),
    @XmlEnumValue("GlacialAndOrPaleosol")
    GLACIAL_AND_OR_PALEOSOL("GlacialAndOrPaleosol"),
    @XmlEnumValue("Hybrid")
    HYBRID("Hybrid"),
    @XmlEnumValue("Ironstone")
    IRONSTONE("Ironstone"),
    @XmlEnumValue("MixedCarbAndOrSiliciclastic")
    MIXED_CARB_AND_OR_SILICICLASTIC("MixedCarbAndOrSiliciclastic"),
    @XmlEnumValue("MnNoduleAndOrCrust")
    MN_NODULE_AND_OR_CRUST("MnNoduleAndOrCrust"),
    @XmlEnumValue("SiliceousBiogenic")
    SILICEOUS_BIOGENIC("SiliceousBiogenic"),
    @XmlEnumValue("Siliciclastic")
    SILICICLASTIC("Siliciclastic"),
    @XmlEnumValue("Volcaniclastic")
    VOLCANICLASTIC("Volcaniclastic");
    private final String value;

    SedimentaryDetails(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SedimentaryDetails fromValue(String v) {
        for (SedimentaryDetails c: SedimentaryDetails.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
